### ISSUE TITLE
No way to correctly detokenize unicode characters that are split into multiple tokens.

### ISSUE THREAD

**Issue by nkoppel** [edgenai/llama_cpp-rs#31]
Certain emojis, such as "🦙" are split into multiple tokens when tokenized. The current API does not provide a way to detokenize strings like this. The nearest you can get to a correct detokenization algorithm is the following:

```rust
// This line panics in the current version because out_buf in tokenize_bytes is too small
let tokenized = model.tokenize_bytes("🦙").unwrap();
let detokenized = tokenized
    .iter()
    .map(|token| model.token_to_piece(*token))
    .fold(String::new(), |s, sp| s + &sp);
```

and this outputs " ����".

**Comment by nkoppel** [comment]
Note that I got this result with [Mistral Instruct 0.2](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/blob/main/mistral-7b-instruct-v0.2.Q5_K_M.gguf). Also note that I have some draft code to solve this issue published on my [detokenization_utils](https://github.com/edgenai/llama_cpp-rs/compare/main...nkoppel:llama_cpp-rs:detokenization_utils) branch. Let me know if those solutions would be useful to you and if you want me to open a pull request.

**Comment by pedro-devv** [comment]
They would be useful yes, as I'd have to look at this issue eventually :stuck_out_tongue: , this is something I was somewhat aware of, but wasn't focusing on. I took a look at your branch, feel free to open a PR :+1:  . 

Any contributions are appreciated!
