### ISSUE TITLE
'block_on' loops infinitely after a certain number of calls when used in an async context

### ISSUE THREAD

**Issue by nkoppel** [edgenai/llama_cpp-rs#53]
I know that this issue isn't with llama_cpp-rs, but I think that this is relevant because it was likely the root cause of #41 and will cause the following example code to hang after receiving 100-150 tokens. I think that users are fairly likely to make this mistake without realizing it, so I'd be interested to hear options for how to deal with this.

```rust
use std::io::Write;

use llama_cpp::standard_sampler::{StandardSampler, SamplerStage};
use llama_cpp::*;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let model = LlamaModel::load_from_file(
        "path/to/models/mistral-7b-instruct-v0.2.Q5_K_M.gguf",
        LlamaParams::default(),
    )
    .expect("Could not load model");

    let mut ctx = model.create_session(SessionParams {
        n_ctx: 16384,
        .. SessionParams::default()
    }).unwrap();

    ctx.set_context("[INST] Write an essay about the importance of hydration in the style of a high school student. [/INST]").unwrap();
    let completion = ctx.start_completing_with(StandardSampler::default(), 1024);

    for (i, str) in completion.into_strings().enumerate() {
        println!("{i} {str:?}");
        // std::io::stdout().flush().unwrap();
    }
}
```

**Comment by nkoppel** [comment]
What do you think of changing the `tokio` versions of the locks and streams into their `std` counterparts? Then, we could implement the blocking, synchronous api as normal, and implement asynchronous counterparts using `tokio::spawn_blocking`. This would make it so that users can trigger deadlocks when mixing the synchronous and asynchronous apis, but this may be easier to warn against than the current behavior.

**Comment by pedro-devv** [comment]
`tokio` locks and channels already provide both sync and async read/write/receive functions, so there should be no need to change them.
