### ISSUE TITLE
Sampler Expansion - GBNF Grammar

### ISSUE THREAD

**Issue by ianmarmour** [edgenai/llama_cpp-rs#54]
Currently the Sampler does not actually support sampling with grammar what's currently in place just seems like a placeholder and not actually used in sampling. I'm not sure if this fits directly in with #38 but would be another nice improvement. There's a few different options for implementing this we could probably take a dependency on [the llama.cpp parser](https://github.com/ggerganov/llama.cpp/blob/67be2ce1015d070b3b2cd488bcb041eefb61de72/common/sampling.cpp#L10-L11) or we could try and roll a [custom GBNF parser](https://github.com/utilityai/llama-cpp-rs/blob/7ed563ed9c86558b0a6923fcddb3662274a83fb0/llama-cpp-2/src/grammar.rs#L101) I'm not sure what would really be ideal here.

**Comment by pedro-devv** [comment]
It's probably better to use a custom parser, as the `llama.cpp` parser does not have a C API, only CPP. Don't think it fits #38, but should be easy to further expand sampling after that is solved.

**Comment by nkoppel** [comment]
@pedro-devv I think that this will fit #50, and this functionality can be implemented as a new `SamplerStage`. I would probably design it to store an opaque object that stores the parsed grammar and the current state.

**Comment by nkoppel** [comment]
Well, sampler stages have access to the tokens in the current context. We should be able to handle this entirely within a `SamplerStage` if we call `llama_grammar_accept_token` with the last token in context if it exists. There may still be some complexities with this implementation, such as how to initialize the grammar's state, how to clone that `SamplerStage`, etc.
