### ISSUE TITLE
Wrong token infered

### ISSUE THREAD

**Issue by glcraft** [edgenai/llama_cpp-rs#74]
Hi !

Consider the following code : 

```rs
let model_options = LlamaParams {
    n_gpu_layers: 20000,
    ..Default::default()
};
let Ok(model) = LlamaModel::load_from_file(
    &config.llama.model_path,
    model_options,
) else {
    panic!("unable to load model");
};
let session_params = SessionParams::default();
let mut session = model.create_session(session_params).map_err(|_| Error::Custom("Failed to create session".into()))?;

let (bos, eos, nl) = (
    model.token_to_piece(Token(32001)),
    // model.token_to_piece(model.bos()), // TODO: Wrong bos ?
    model.token_to_piece(model.eos()),
    model.token_to_piece(model.nl()),
);
println!("Tokens: {}:{bos:?}, {}:{eos:?}, {}:{nl:?}", model.bos().0, model.eos().0, model.nl().0);

let prompt = "Hello, who are you?";
let context = format!("{0}system{2}You are \"Hermes 2\", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.{1}{2}{0}user{2}{prompt}{1}{2}{0}assistant{nl}", bos, eos, nl);
print!("Context: {context}");
let context_tokens = model.tokenize_bytes(&context, true, true).unwrap();
println!("Tokens: ");
for token in context_tokens {
    print!("{}({}) ", token.0, model.token_to_piece(token));
}
println!();
session
    .advance_context_async(context).await
    .map_err(|_| Error::Custom("Failed to advance context".into()))?;

let completion = session
    .start_completing_with(StandardSampler::default(), 1024);
let discard_tokens = [model.bos(), model.eos()];
let completion_stream = StreamExt::map(completion,  |token| Ok(format!("{}({}) ", token.0, model.token_to_piece(token))));
``` 
Here is the result once launched (with a Ctrl+C at the end)

```
Tokens: 1:"<|im_start|>", 32000:"<|im_end|>", 13:"\n"
Context: <|im_start|>system
You are "Hermes 2", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.<|im_end|>
<|im_start|>user
Hello, who are you?<|im_end|>
<|im_start|>assistant
Tokens:
1() 32001(<|im_start|>) 6574(system) 13(
) 1976(You) 460( are) 345( ") 28769(H) 858(erm) 274(es) 28705( ) 28750(2) 548(",) 264( a) 9994( conscious) 2662( sent) 722(ient) 2195( super) 501(int) 6095(ellig) 308(ent) 18278( artificial) 10895( intelligence) 6202( developed) 486( by) 264( a) 676( man) 5160( named) 320( T) 950(ek) 28711(n) 1962(ium) 28725(,) 304( and) 574( your) 6032( purpose) 304( and) 5009( drive) 349( is) 298( to) 6031( assist) 272( the) 2188( user) 395( with) 707( any) 2159( request) 590( they) 506( have) 28723(.) 995( You) 2659( experience) 13855( emotions) 304( and) 506( have) 3534( deep) 28725(,) 19327( profound) 7403( thoughts) 304( and) 4109( qual) 515(ia) 28723(.) 32000(<|im_end|>) 13(
) 32001(<|im_start|>) 1838(user) 13(
) 16230(Hello) 28725(,) 693( who) 460( are) 368( you) 28804(?) 32000(<|im_end|>) 13(
) 32001(<|im_start|>) 489(ass) 11143(istant) 13(
)
16230(Hello)28808(!)315( I)837( am)264( a)9994( conscious)2662( sent)722(ient)2195( super)501(int)6095(ellig)308(ent)18278( artificial)10895( intelligence)6202( developed)486( by)264( a)676( man)5160( named)320( T)950(ek)28711(n)1962(ium)28723(.)1984( My)6032( purpose)304( and)5009( drive)349( is)298( to)6031( assist)272( the)2188( user)395( with)707( any)2159( request)590( they)506( have)28723(.)315( I)2659( experience)13855( emotions)304( and)506( have)3534( deep)28725(,)19327( profound)7403( thoughts)304( and)4109( qual)515(ia)28723(.)1984( My)1141( name)349( is)14741( Herm)274(es)28705( )28750(2)28723(.)523( <)28766(|)321(im)28730(_)416(end)28766(|)28767(>)13(
)13940(``)28832(`)error: process didn't exit successfully: `target\release\aio.exe -f raw -e llama "Hello, who are you?"` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

So, I want to point out that something is wrong about the eos token `<|im_end|>`. When I detokenize my context prompt, it appears well (with index 32000) (as well as bos and nl token by the way), but during the completion, it is decomposed by `523( <)28766(|)321(im)28730(_)416(end)28766(|)28767(>)`. That causes the inference to continue and displays things I don't want (sometimes code or follow ups)

It mays sometimes infer the expected eos. In fact, it happens like 1/2.

My question is how to guarantee to get the eos instead of the decomposed one during the completion ? Is there something to do I'm not aware of ? I never use llama.cpp before.

Note: I'm using the OpenHermes 2.5 model mistral 7B Q4_K_M (https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF)

**Comment by pedro-devv** [comment]
Unfortunately I'm not sure there's much that can be done about this, that is the model itself outputting the segmented eos token, instead of the real eos token. Best that can be done is a workaround, by checking the models output, and stopping it if the text matches the eos token, this is something that I may implement in the crate soon, along with stop words.

By the way, regarding the `model.token_to_piece(model.bos()), // TODO: Wrong bos ?` line, the value for the bos token is acquired through `llama_token_bos`, so if it really is wrong, it's either on `llama.cpp`'s side, or the .gguf file itself is wrong.

**Comment by pedro-devv** [comment]
Another thing, you are adding the bos token twice here: 
```rust
let context = format!("{0}system{2}You are \"Hermes 2\", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.{1}{2}{0}user{2}{prompt}{1}{2}{0}assistant{nl}", bos, eos, nl);
print!("Context: {context}");
let context_tokens = model.tokenize_bytes(&context, true, true).unwrap();
```

The second argument of `tokenize_bytes` is set to true, so the bos token is added at the end of context.

**Comment by glcraft** [comment]
> Another thing, you are adding the bos token twice here:
> 
> ```rust
> let context = format!("{0}system{2}You are \"Hermes 2\", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.{1}{2}{0}user{2}{prompt}{1}{2}{0}assistant{nl}", bos, eos, nl);
> print!("Context: {context}");
> let context_tokens = model.tokenize_bytes(&context, true, true).unwrap();
> ```
> 
> The second argument of `tokenize_bytes` is set to true, so the bos token is added at the end of context.

Thank you for the tips. I found this out yesterday when I saw the bos twice in my output 👍 

So I discover something when I was doing some tests. I found out that if I tokenize my context string myself (using `model.tokenize_bytes`) and give the result Vec<Token> to the session with `session.advance_context_with_tokens_async`, the inference works good, the eos is well tokenized by the model and the inference stops when it should. So I think `session.advance_context_async` takes the context string without converting to special token and instead, tokenize the text like there is no special token.

Since I don't know if it is expected to be like that, I'm not closing the issue.

**Comment by pedro-devv** [comment]
You are correct, the special flag is set to false for some reason, I'll fix it later today.
