### ISSUE TITLE
Metal build is broken

### ISSUE THREAD

**Issue by ri-nat** [edgenai/llama_cpp-rs#75]
Hi there!

I'm getting the following error during the start of an app, that has the `llama_cpp` (edge, from the `main` branch) as a dependency:

```
$ cargo run --example llm --features metal                                                                                                                       
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/examples/base`
2024-04-20T00:39:53.167655Z ERROR llama.cpp: ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
2024-04-20T00:39:53.167735Z ERROR llama.cpp: llama_new_context_with_model: failed to initialize Metal backend
thread 'main' panicked at examples/base.rs:23:66:
called `Result::unwrap()` on an `Err` value: SessionFailed
```

Nothing unusual with the environment or my code itself - everything works great on earlier commits (pre–https://github.com/edgenai/llama_cpp-rs/commit/a493f97, if I recall correctly).

I believe it is some minor thing, but my limited Rust/C++ interop experience didn't allow me to dig into it deeper, so I would appreciate any help or even just a suggestion on how to fix this.

---

Really nice crate, btw, thank you for your work!

**Comment by pedro-devv** [comment]
Hello, I have made some changes in #78 that should hopefully fix the issue. Please check if it still occurs, as I cannot test it myself.

**Comment by benpoulson** [comment]
I have a similar issue targeting `main`.

```
cargo check --message-format json --workspace --all-targets -Z unstable-options --keep-going
   Compiling llama_cpp_sys v0.3.1 (https://github.com/edgenai/llama_cpp-rs#e2a5cb7f)
error: failed to run custom build command for `llama_cpp_sys v0.3.1 (https://github.com/edgenai/llama_cpp-rs#e2a5cb7f)`
error: failed to run custom build command for `llama_cpp_sys v0.3.1 (https://github.com/edgenai/llama_cpp-rs#e2a5cb7f)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/[redacted]/target/debug/build/llama_cpp_sys-30454a3f38065cda/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./thirdparty/llama.cpp
  Generating bindings..
  Compiling Metal GGML..
  --- stderr
  thread 'main' panicked at /[redacted]/.cargo/git/checkouts/llama_cpp-rs-b9d51cabb4b43824/e2a5cb7/crates/llama_cpp_sys/build.rs:513:9:
  An error has occurred while embedding common file (exit status: 1):
  sed: 1: "'/#include "ggml-common ...": invalid command code '
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
     1: core::panicking::panic_fmt
               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
     2: build_script_build::compile_metal
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
```

**Comment by benpoulson** [comment]
Fix provided in #79 @pedro-devv

**Comment by benpoulson** [comment]
I also had to change the tokio features, because of the usage of `tokio::task::block_in_place`
But I can't work out whether it's just me being an amateur, or an actual problem.

![image](https://github.com/edgenai/llama_cpp-rs/assets/1797843/9c356a60-6f59-40b8-9447-ba25eedc288c)

![image](https://github.com/edgenai/llama_cpp-rs/assets/1797843/cdbd5f51-cbd8-4c03-b7aa-6342ef6ae8b3)

**Comment by pedro-devv** [comment]
Thank you for the PR! 
Regarding the `tokio` feature, it should be enabled in the crate, coincidentally I never had issues related to it, that's why the feature isn't already enabled, I'll do that in a bit.

**Comment by pedro-devv** [comment]
I'm closing this issue as it seems to be resolved.

**Comment by ri-nat** [comment]
Confirmed: it works perfectly now. Thank you @benpoulson & @pedro-devv!
