### ISSUE TITLE
What's the difference between `set_context` and `advance_context`?

### ISSUE THREAD

**Issue by hazelnutcloud** [edgenai/llama_cpp-rs#85]
Just trying to understand the difference. Thanks!

**Comment by pedro-devv** [comment]
`advance_context` will essentially "append" the new context to the end of already existing context within the session. 
`set_context` will reset/clear the session's existing context and then advance with the new context.

**Comment by hazelnutcloud** [comment]
Thank you for answering! I understand it better now.
